### PR TITLE
benchmark function that gets code from file and input/expected from command args

### PR DESCRIPTION
**Pull request by cdetrio**
use like: `test/evmone-bench codefile.hex calldatahex expectedreturnhex`
```
~/evmone/build# test/evmone-bench sha1code.hex 1605782b00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000006010203040506  5d211bad8f4ee70e16c7d343a838fc344a1ed961000000000000000000000000 --benchmark_filter=bench_evm_code
```

### CODE REVIEW

**Comment by cdetrio** [comment]
Put the [hex EVM code](https://github.com/chfast/evmone/blob/ce8deb4a6c902d09facffad29d022eabaa29f5d9/test/benchmarks/benchmarks.cpp#L22) into an ascii file:

```
echo "608060405234801561001057600080fd5b506004361061002b5760003560e01c80631605782b14610030575b600080fd5b6100d66004803603602081101561004657600080fd5b81019060208101813564010000000081111561006157600080fd5b82018360208201111561007357600080fd5b8035906020019184600183028401116401000000008311171561009557600080fd5b91908080601f0160208091040260200160405190810160405280939291908181526020018383808284376000920191909152509295506100f8945050505050565b604080516bffffffffffffffffffffffff199092168252519081900360200190f35b60006040518251602084019350604067ffffffffffffffc06001830116016009828203106001811461012957610130565b6040820191505b50776745230100efcdab890098badcfe001032547600c3d2e1f0610183565b60008383101561017c5750808201519282900392602084101561017c5760001960208590036101000a0119165b9392505050565b60005b8281101561045c5761019984828961014f565b85526101a984602083018961014f565b6020860152604081850310600181146101c1576101ca565b60808286038701535b50604083038114600181146101de576101ee565b8460031b60208701511760208701525b5060405b608081101561027157858101603f19810151603719820151601f19830151600b1984015118911818600181901b7ffffffffefffffffefffffffefffffffefffffffefffffffefffffffefffffffe16601f9190911c7c010000000100000001000000010000000100000001000000010000000116179052600c016101f2565b5060805b6101408110156102f557858101607f19810151606f19820151603f1983015160171984015118911818600281901b7ffffffffcfffffffcfffffffcfffffffcfffffffcfffffffcfffffffcfffffffc16601e9190911c7c030000000300000003000000030000000300000003000000030000000316179052601801610275565b508160008060005b60508110156104325760148104801561032d576001811461034e576002811461036d5760038114610391576103ac565b602885901c605086901c8118607887901c16189350635a82799992506103ac565b8460501c8560781c189350838560281c189350636ed9eba192506103ac565b605085901c607886901c818117602888901c169116179350638f1bbcdc92506103ac565b8460501c8560781c189350838560281c18935063ca62c1d692505b50601f8460bb1c168063ffffffe086609b1c1617905080840190508063ffffffff86160190508083019050808260021b8b015160e01c0190508060a01b8560281c179450633fffffff8560521c1663c00000008660321c161760501b77ffffffff00ffffffff000000000000ffffffff00ffffffff8616179450506001810190506102fd565b5050509190910177ffffffff00ffffffff00ffffffff00ffffffff00ffffffff1690604001610186565b5063ffffffff811667ffffffff000000008260081c166bffffffff00000000000000008360101c166fffffffff0000000000000000000000008460181c1673ffffffff000000000000000000000000000000008560201c161717171760601b94505050505091905056fea165627a7a72305820227af8b272b9b0e3d345f580ebcde55f50e3e8b7ecafabffcadb92e55e4de68e0029" \
> sha1code.hex

~/evmone/build# test/evmone-bench sha1code.hex 1605782b00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000006010203040506  5d211bad8f4ee70e16c7d343a838fc344a1ed961000000000000000000000000 --benchmark_filter=bench_evm_code
```

**Comment by chfast** [comment]
Thanks @cdetrio, 
I think this is really good idea to allow loading benchmark from files. I will try to integrate it soon. 
What do you think about allowing loading all files from a directory and run all benchmarks?

I suppose it will also help @zac-williamson as he was adding his own benchmarks.

I should also allow running benchmarks from https://github.com/ethereum/aleth/tree/master/test/unittests/performance by @gcolvin.

**Comment by gcolvin** [comment]
Thanks @cdetrio, I missed this until @chfast mentioned me.  I would like to see those benchmarks too, as I've been using them for a while.  Do all tests have to be in hex?  Can we keep source around when we have it?

**Comment by cdetrio** [comment]
> What do you think about allowing loading all files from a directory and run all benchmarks?

My benchmarking script already does them one by one, but this feature might be useful to somebody else.

**Comment by chfast** [comment]
I pushed some improvements:
- the benchmark renamed to "external_evm_code",
- the benchmark is registered only when proper args provided (still have to be filtered),
- error is reported by benchmark library API,
- the output check is removed from the benchmarking loop.

Let me know if this looks ok and works.

**Comment by axic** [comment]
@cdetrio @chfast can this be merged so that we can refer to an evmone version in the benchmarking report?

**Comment by cdetrio** [comment]
👍

**Pull request merged**
